// Airport Actions
export const GET_AIRPORTS_REQUEST = 'GET_AIRPORTS_REQUEST';
export const GET_AIRPORTS_SUCCESS = 'GET_AIRPORTS_SUCCESS';
export const GET_AIRPORTS_FAILURE = 'GET_AIRPORTS_FAILURE';

export const SEARCH_AIRPORTS_REQUEST = 'SEARCH_AIRPORTS_REQUEST';
export const SEARCH_AIRPORTS_SUCCESS = 'SEARCH_AIRPORTS_SUCCESS';
export const SEARCH_AIRPORTS_FAILURE = 'SEARCH_AIRPORTS_FAILURE';

// Flight Actions
export const SEARCH_FLIGHTS_REQUEST = 'SEARCH_FLIGHTS_REQUEST';
export const SEARCH_FLIGHTS_SUCCESS = 'SEARCH_FLIGHTS_SUCCESS';
export const SEARCH_FLIGHTS_FAILURE = 'SEARCH_FLIGHTS_FAILURE';

export const SET_SELECTED_FLIGHT = 'SET_SELECTED_FLIGHT';
export const CLEAR_FLIGHT_SEARCH = 'CLEAR_FLIGHT_SEARCH';

// Booking Actions
export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'CREATE_BOOKING_FAILURE';

export const GET_BOOKING_REQUEST = 'GET_BOOKING_REQUEST';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAILURE = 'GET_BOOKING_FAILURE';

// UI Actions
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
